# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"  # to download reads from SRA the accession numbers (see https://www.ncbi.nlm.nih.gov/sra) of samples must be given in units.tsv
single_end: False

resources:
  #Path to the share resources folder for the pipeline, where common files (genomes, references) are stored.
  #Please do not change.
  path: /data1/share/dcyleung/Pipeline/snakemake/resources/
  ref:
    # Genecode or UCSC assembly name
    assembly: GRCh38


params:
  trimming:
    activate: True
  #Chose between bismark or bwameth to use for mapping. bwameth will use methyldackel to extract methylation metrics.
  mode: "bismark"
  # Params to use for bismark. Only used when the mode is set to bismark.
  bismark:
    #Params for mapping
    map:
      # optional params string, e.g: -L 20 -N 0 -I 0 -X 500 (default values)
      # For both SE and PE reads (don't set PE only parameters for SE)
      # Useful options to tune:
      # (for bowtie2)
      # -N: The maximum number of mismatches permitted in the "seed", i.e. the first L base pairs
      # of the read (deafault: 0)
      # -L: The "seed length" (deafault: 20)
      # -I: The minimum insert size for valid paired-end alignments. ~ min fragment size filter (for
      # PE reads)
      # -X: The maximum insert size for valid paired-end alignments. ~ max fragment size filter (for
      # PE reads)
      # --gzip: Gzip intermediate fastq files
      # --ambiguous --un : add ambiguous or unmapped reads output
      # --non_directional : for non directional libraries
      # Further info https://rawgit.com/FelixKrueger/Bismark/master/Docs/Bismark_User_Guide.html#appendix-ii-bismark
      # The parameter --multicore 4 is hard set for this step
      extra: "--gzip"
    extract:
      #Params for methylation extraction. Used for both PE and SE. There are some default parameters already set:
      #SE: --gzip --bedGraph --counts 
      #PE: --no-overlap --gzip --bedGraph --counts 
      #Specifying this option will merge all four possible strand-specific methylation info into context-dependent output files: CpG, CHG, CHH
      comprehensive: True
      #Produces a genome-wide methylation report for all cytosines in the genome
      cytosine_report: False
      #The minimum number of times any methylation state (methylated or unmethylated) has to be seen for a nucleotide before its methylation percentage is reported
      cutoff: 1
      #Any extra parameters not mentioned here
      extra: ""
  # Params to use for methildackel. Only used when the mode is set to bwameth.
  methyldackel:
    # Adds CHG and CHH methylation in addition to CpG. Will produce very large files.
    comprehensive: True
    # Sets the minimum coverage for methylation calls.
    min_depth: 0
    # Ignores the aligner flags for low quality reads, duplicates, etc. Recommended to leave at False.
    ignore_flags: False
    # Makes the output compatible with MethylKit. This option has to be true for differential methylation analysis to work in bwameth mode
    methyl_kit: False
    # Extra parameters for Methyldackel extrat and mbias plot functions. Further explanation on the parameters can be found here https://github.com/dpryan79/MethylDackel
    extra_extract: ""
    extra_mbias: ""
  #Perform differential methylation analysis
  diff_meth:
    activate: True
    #Minimum coverage for a base to be considered for the analysis. Default: 10
    min_cov: 10
    #By default methylkit merge samples function produces bases/regions covered in all samples. To relax this setting, put a number indicating tha the
    #region/base should be in at least x samples. Otherwise leave empty (full empty, no "" or '') for default all.
    min_group:
    #If the tile window parameter is higher than 1, methylkit will be run for tiling windows methylation instead of per base methylation
    tile_window: 1
    #Step size for the tiling windows analysis
    step_size: 1000
    #Minimum coverage used to call methylation for tiling windows. 
    #Methylkit recommends setting a lower min_cov (parameter above) for methylation reading, and then setting a higher min_cov when calling methylation
    #for the tiling windows. The default recommended parameters are min_cov = 3 and tile_cov = 10
    tile_cov: 10
  lc_extrap:
    # computes the expected future yield of distinct reads and bounds on the number of total distinct reads in the library and the associated confidence intervals.
    activate: True
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalised letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  ##### IMPORTANT FOR WGBS #####
  #Some experimental protocols need some bases trimmed from both 5' and 3' ends to avoid bias.
  #You can do this by adding --cut (number of bases) if you do not have adapters in the fastqs or using the following pattern:
  #ADAPTERN{number} where number is the number of N bases (any) that you want to remove after the adapter. You can also do this for before the adapter.
  #IE: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAN{8} for after the adapter; N{8}AGATCGGAAGAGCACACGTCTGAACTCCAGTCA for before the adapter. More explanations in the link above
  cutadapt-se: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  cutadapt-pe: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  # reasoning behind parameters:
  #   * `-e 0.005`: the default cutadapt maximum error rate of `0.2` is far too high, for Illumina
  #     data the error rate is more in the range of `0.005` and setting it accordingly should avoid
  #     false positive adapter matches
  #   * `--minimum-overlap 7`: the cutadapt default minimum overlap of `5` did trimming on the level
  #     of expected adapter matches by chance
  cutadapt-others: "-e 0.005 --overlap 7"
