restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 2
latency-wait: 60
use-conda: true
rerun-incomplete: true
cache: true
jobs: 10
printshellcmds: true
#Change path depending on cluster
#conda-prefix: /home/share/dcyleung/snakemake/resources/envs
#conda-prefix: /home4/share/dcyleung/snakemake/resources/envs
#conda-prefix: /data1/share/dcyleung/Pipeline/snakemake/resources/envs
#For clusters that allow containers
use-singularity: true