# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"  # to download reads from SRA the accession numbers (see https://www.ncbi.nlm.nih.gov/sra) of samples must be given in units.tsv
single_end: False

resources:
  #Path to the share resources folder for the pipeline, where common files (genomes, references) are stored.
  #Please do not change.
  path: /data1/share/dcyleung/Pipeline/snakemake/resources/
  ref:
    # Genecode or UCSC assembly name
    assembly: GRCh38
    # specify release version number of igenomes list to use (see https://github.com/nf-core/chipseq/releases), default: 1.2.2
    igenomes_release: 1.2.2
    # if igenomes.yaml cannot be used, a value for the mappable or effective genome size can be specified here, e.g. macs-gsize: 2.7e9
    macs-gsize:
    # if igenomes.yaml cannot be used, a path to an own blacklist can be specified here
    blacklist:

params:
  trimming:
    activate: True
  # Number of biological replicates required from a given condition for a peak to contribute to a consensus peak
  min-reps-consensus: 1
  # Maximum p-value and q-value (FDR adjusted p-value) for genrich peak calling
  callpeak:
    p-value: 0.01
    q-value: 1
    #Comma-separated list of chromosomes to exclude, Mithochondrial is recommended for ATAC
    chromosome: chrM
  deeptools-plots:
    # when activated the plot profile and heatmap plot are generated, this involves a matrix calculation that requires a lot of working memory.
    # May crash due to high memory usage, not recommended unless you do a more exhaustive filtering.
    activate: False
  lc_extrap:
    # computes the expected future yield of distinct reads and bounds on the number of total distinct reads in the library and the associated confidence intervals.
    activate: True
  picard_metrics:
    # Produces alignment metrics
    activate: True
  deseq2:
    # optional to run vst transform instead of rlog
    vst: False
  peak-annotation-analysis:
    activate: True
  peak-qc:
    activate: True
  consensus-peak-analysis:
    # Should not be run unless there are at least 2 samples per control (not counting control) otherwise will not work.
    activate: True
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalised letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  cutadapt-se: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
   # reasoning behind parameters:
  #   * `-e 0.005`: the default cutadapt maximum error rate of `0.2` is far too high, for Illumina
  #     data the error rate is more in the range of `0.005` and setting it accordingly should avoid
  #     false positive adapter matches
  #   * `--minimum-overlap 7`: the cutadapt default minimum overlap of `5` did trimming on the level
  #     of expected adapter matches by chance
  cutadapt-pe: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  cutadapt-others: "-e 0.005 --overlap 7"
