from snakemake.utils import min_version

min_version("6.4.0")

# The main entry point of workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"

report: "report/workflow.rst"

container: "docker://continuumio/miniconda3"

include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/qc.smk"
include: "rules/cutadapt.smk"
include: "rules/mapping.smk"
include: "rules/stats.smk"
include: "rules/filtering.smk"
include: "rules/peak_calling.smk"
include: "rules/post-analysis.smk"
include: "rules/diff_analysis.smk"

rule all:
    input: all_input
