from snakemake.utils import min_version

##### set minimum snakemake version #####
min_version("5.12.0")


##### setup report #####
configfile: "config/config.yaml"


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
# No use since Docker and singularity are no longer supportend on CentOS 6, use if they update.
containerized: f"{config['resources']}containers/rna-seq.sif"


##### load rules #####


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/trim.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/filter.smk"
include: "rules/diffexp.smk"
include: "rules/Gbrowser.smk"
include: "rules/single.smk"
include: "rules/single_TE.smk"

##### target rules #####

rule all:
    input: all_input
