# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"  # to download reads from SRA the accession numbers (see https://www.ncbi.nlm.nih.gov/sra) of samples must be given in units.tsv

resources:
  #Path to the share resources folder for the pipeline, where common files (genomes, references) are stored.
  #Please do not change.
  path: /data1/share/dcyleung/Pipeline/snakemake/resources/
  ref:
    # Genecode or UCSC assembly name
    assembly: GRCh38

params:
  trimming:
    activate: True
  #Options for the fanc Hi-C pipeline
  fanc:
    #Further explanation of these commands can be found here https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_modular_steps.html
    #Comma separated list of restriction enzymes used in Hi-C, used to split reads by predicted ligation junction before mapping.
    #It can be any enzyme supported by REBASE, case sensitive (http://rebase.neb.com/rebase/rebase.html)
    enzyme: "HinfI,DpnII"
    # Comma-separated list of chromosomes to include in fragments BED file (used to create pairs files). Chromosomes in the list will be included. If empty all will be included.
    chr: ""
    #Should the pairs files of samples in the same group be merged before creating hic objects?
    #It also changes the behavior of the analysis.
    #False -> Do the PCA and the expected values for the samples.
    #True -> Do all the analysis to merged groups, except PCA.
    merge_groups: True
    #Comma separated list of regions for which to do the matrix analysis. Leave empty to not specify a particular region (whole genome will be used).
    #The format is <chromosome>:<start>-<end> (check default)
    #Note that the TADs plots need specific regions (i.e. not whole chromosomes) to work.
    regions: "chr1:5kb-1Mb,chr2:0-5000000,chr3"
    map:
      #Defaults values are set for bwa
      # Minimum length of read before extension
      min_size: 25
      # Number of base pairs to extend at each round of mapping
      step_size: 10
      # Mapping quality cutoff
      quality: 3
      # Extra parameters to pass to fanc map
      extra : ""
    #Filtering parameters for the pairs step
    filter:
      #Filters for bam files when making the pair file, many options
      # Should unmapped reads be filtered out
      unmap: True
      # Should multimapping reads be filtered out. It can be set to 'strict' to perform strict multimapping reads filtering
      multimap: True
      # Minimum distance for inward-facing read pairs. Leave empty to not filter.
      inward:
      # Minimum distance for outward-facing read pairs. Leave empty to not filter.
      outward:
      # Maximum distance for a read to the nearest restriction site. Leave empty to not filter.
      distance:
      # Remove read pairs representing self-ligated fragments. Leave empty to not filter.
      ligation: 
      # Filter read pairs for PCR duplicates. Parameter determines distance between alignment starts below which they are considered starting at same position. 
      # Sensible values are between 1 and 5. Leave empty to not filter.
      pcr:
      # Extra parameters for filtering
      extra: ""
    hic:
      #Should a juicer hic file also be produced in addition to fanc hic. The juicer file will be filtered according to the previous settings.
      #The juicer file will include all normalizations and bin sizes available in juicer.
      juicer: True
      # bin size (resolution) can be given as a number or as a common abbreviation (see default).
      #Several resolutions can be set, separate by comma (,).
      bin_size: "5mb,2mb,1mb,500kb,250kb,100kb,50kb,25kb,10kb,5kb"
      # 2 options for filtering
      # -l <number> threshold for absolute number of pairs per bin minimum coverage
      # -r <fraction> (between 0 and 1) threshold for fraction of the median number of pairs per bin
      filter: "-r 0.1"
      # Filter bins along the diagonal up to this specified distance. Use 0 for only filtering the diagonal. Empty for no diagonal filtering
      diagonal:
      #Balance Hi-C matrices
      normalize:
        activate: True
        #Method to use in normalization, options: 
        #KR (default) = Knight-Ruiz matrix balancing (Fast, accurate, but memory-intensive normalization) 
        #ICE = ICE matrix balancing (less accurate, but more memory-efficient) 
        #VC = vanilla coverage (a single round of ICE balancing)
        #VC-SQRT = vanilla coverage square root (reduces overcorrection compared to VC)
        method: "KR"
        #Apply the correction to the whole matrix instead of individual chromosomes
        whole: False
      #Extra parameters for fanc Hic
      extra: ""
    analysis:
      #All the steps in analysis will be performed with the fanc hic file, so only for 1 resolution/normalization.
      #Activate or deactivate matrix analysis in the pipeline. If deactivated, it will only produce hic files.
      activate: True
      #bin size to use for the analysis. It should be one of the listed above for the hic generation.
      bin_size: "5kb"
      #To check PCA params go here https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/pca.html
      #Names and plot are already automatically added. The PCA will be done for the whole genome unless you specify a region/s (comma separated) here.
      pca_params: "-Z"
      #Chromosome for expected values calculation. Only one chromosome. This parameter is required.
      expected_params: "chr1"
      #Parameters for the AB compartments. More info can be found here https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-analyse-hic/ab_compartments.html
      #The pipe automatically generates the matrix, eigenvector, ab file, domains and profile plot. You can specify some parameters for them here.
      AB_params: ""
      #This parameters deals only with the fanc plot matrix part of AB compartment section.
      AB_plot: "-vmin -0.75 -vmax 0.75 -c RdBu_r"
      #Params only for the annotation part.
      Loop_annotate: ""
      #Params for loop filtering:
      Loop_filter: "--rh-filter -d 5 -o 5"
      #Params for the loop merging:
      Loop_merge: "-j --remove-singlets"
      #Params for hitad and domaincaller (TADs calling)
      #Should domaincaller be used to detect TADs only, or hitad instead to detect hierarchical TADs (TADs, sub-TADs, small domains)
      #Note: hitad may make the pipe much slower since it needs single sample matrices too.
      hierarchical_TADs: False
      #Extra params for domaincaller. Defaults are set.  Specify "--weight-col RAW" if you want to run with the raw matrix.
      domaincaller_extra: "--weight-col weight --exclude ['chrY','chrM']"
      #Extra params for hitad. Defaults are set.
      hitad_extra: "--maxsize 4000000"
      #Params for plotting TADs. The plotting needs at least a region to be set.
      #Useful params here are:
      #--dpi <resolution>, default: 300
      #--arrowhead : to use the arrowhead transformed matrix (only for hierarchical TADs)
      #--vmin <value> minimum value that the colorvar covers
      #--vmax <value> maximum value that the colorvar covers
      TAD_plot: "--dpi 300 --vmin 0 --vmax 0.05"
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalized letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  cutadapt-se: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
   # reasoning behind parameters:
  #   * `-e 0.005`: the default cutadapt maximum error rate of `0.2` is far too high, for Illumina
  #     data the error rate is more in the range of `0.005` and setting it accordingly should avoid
  #     false positive adapter matches
  #   * `--minimum-overlap 7`: the cutadapt default minimum overlap of `5` did trimming on the level
  #     of expected adapter matches by chance
  cutadapt-pe: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  cutadapt-others: "-e 0.005 --overlap 7"
