# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"  # to download reads from SRA the accession numbers (see https://www.ncbi.nlm.nih.gov/sra) of samples must be given in units.tsv
single_end: False

resources:
  #Path to the share resources folder for the pipeline, where common files (genomes, references) are stored.
  #Please do not change.
  path: /data1/share/dcyleung/Pipeline/snakemake/resources/
  ref:
    # Genecode or UCSC assembly name
    assembly: GRCh38

params:
  trimming:
    activate: True
  # Maximum p-value and q-value (FDR adjusted p-value) for genrich peak calling, if q is specified p is ignored. The values used here are genrich defaults
  map:
    #Comma separated list of restriction enzymes used in Hi-C, used to split reads by predicted ligation junction before mapping.
    enzyme: "HinfI,DpnII"
    #Extra mapping parameters:
    #-m (min-size) Minimum length of read before extension
    #-s (step-size) Number of base pairs to extend at each round of mapping
    #-q Mapping quality cutoff
    #Defaults values are set for bwa
    #Further explanation can be found here https://fan-c.readthedocs.io/en/latest/fanc-executable/fanc-generate-hic/fanc_modular_steps.html
    extra: "-m 25 -s 10 -q 3"
  lc_extrap:
    # computes the expected future yield of distinct reads and bounds on the number of total distinct reads in the library and the associated confidence intervals.
    activate: True
  picard_metrics:
    # Produces alignment metrics
    activate: True
  deseq2:
    # optional to run vst transform instead of rlog
    vst: False
  peak-annotation-analysis:
    activate: True
  peak-qc:
    activate: True
  consensus-peak-analysis:
    # Should not be run unless there are at least 2 samples per control (not counting control) otherwise will not work.
    activate: True
  # samtools view parameters:
  # if duplicates should be removed in this filtering, add "-F 0x0400" to the params
  # if for each read, you only want to retain a single (best) mapping, add "-q 1" to params
  # if you would like to restrict analysis to certain regions (e.g. excluding other "blacklisted" regions),
  # the -L option is automatically activated if a path to a blacklist of the given genome exists in "config/igenomes.yaml" or has been entered there
  samtools-view-se: "-b -F 0x004 -F 0x0400 -q 10"
  samtools-view-pe: "-b -f 0x002 -F 0x0400 -q 10"
  # these cutadapt parameters need to contain the required flag(s) for
  # the type of adapter(s) to trim, i.e.:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
  #   * `-a` for 3' adapter in the forward reads
  #   * `-g` for 5' adapter in the forward reads
  #   * `-b` for adapters anywhere in the forward reads
  # also, separate capitalised letter flags are required for adapters in
  # the reverse reads of paired end sequencing:
  # * https://cutadapt.readthedocs.io/en/stable/guide.html#trimming-paired-end-reads
  cutadapt-se: "-g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
   # reasoning behind parameters:
  #   * `-e 0.005`: the default cutadapt maximum error rate of `0.2` is far too high, for Illumina
  #     data the error rate is more in the range of `0.005` and setting it accordingly should avoid
  #     false positive adapter matches
  #   * `--minimum-overlap 7`: the cutadapt default minimum overlap of `5` did trimming on the level
  #     of expected adapter matches by chance
  cutadapt-pe: "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -g AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -G AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  cutadapt-others: "-e 0.005 --overlap 7"
