# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
units: "config/units.tsv"  # to download reads from SRA the accession numbers (see https://www.ncbi.nlm.nih.gov/sra) of samples must be given in units.tsv
#Indicate if sra accession numbers are single or paired end data, it only affects sra. It does not affect local data.
single_end: False

resources:
  #Path to the share resources folder for the pipeline, where common files (genomes, references) are stored.
  #Please do not change.
  path: /data1/share/dcyleung/Pipeline/snakemake/resources/
  ref:
    # Genecode or UCSC assembly name
    assembly: GRCh38


#Config marked as True is activated, config marked as False is deactivated
params:
  #Activate a 2 pass star alignment. It improves novel splice junction quantification.
  #For more info see https://academic.oup.com/bioinformatics/article/32/1/43/1744001
  2nd_pass:
    activate: True
  #Activate adapter trimming. For it to work the trimmer sequences must be set
  #in units.tsv
  trimming:
    activate: False
  #Activate rseqc plots
  rseqc:
    activate: True
  #Make a pca plot. It can only be used when diffexp is also activated.
  pca:
    activate: True
    labels:
      # columns of sample sheet to use for PCA
      - condition
  #Perform Deseq2 analysis. It cannot be activated at the same time of single.
  diffexp:
    activate: True
    # contrasts for the deseq2 results method. Only 2 conditions can be at the same time inside each contrast or the pipeline will fail.
    TE:
      activate: True
      filter: 10
    # You can add more contrasts, e.g control-vs-treatment: - control -treatment. inside the contrasts section.
    contrasts:
      treated-vs-untreated:
        - treated
        - untreated
    model: ~condition
  #Perform single sample differential analysis. Cannot be activated with diffexp.
  single:
    activate: False
    #Alternative is used when doing the Poisson test, can be: greater, less, two.sided . 
    #Greater and less have greater statistical power, but only get up and down regulated genes respectively. two.sided gets both up and down regulated genes.
    alternative: greater
  #Perform single sample TE differential analysis. As before, it cannot be activated with diffexp but you can activate both single and TE_single.
  TE_single:
    activate: False
    filter: 10
    #Same as single alternative, but for TEs (Look above for explanation)
    alternative: greater 
  #The maximum offset between two duplicate clusters in order to consider them optical duplicates. 
  #100 is appropriate for unpatterned versions of the Illumina platform. For the patterned flowcell models, 2500 is more appropriate.
  optical_distance: 2500
  #Cutadapt is used in adapter trimming.
  cutadapt-pe: ""
  cutadapt-se: ""
  #Star is for alignment, recommended parameters are set.
  #The parameters necessary to run the pipeline are coded within the pipeline and
  #cannot be changed. These parameters are:
  #--outSAMunmapped Within KeepPairs --quantMode TranscriptomeSAM --outSAMtype BAM Unsorted
  #Bams are sorted by using samtools sort independently for star, which is identical to "--outSAMtype SortedByCoordinate" star parameter
  star: "--outFilterMultimapNmax 1 --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04
	--alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000
	--sjdbScore 1 --limitBAMsortRAM 60000000000 
  --limitIObufferSize 330000000"
  #Rsem is used for counts, recommended parameters are set.
  #The parameters necessary to run the pipeline are coded within the pipeline and
  #cannot be changed. These parameters are:
  #--bam
  #Rsem seed is set randomly by the system, and strandedness is set from units.tsv file
  #If rsem has trouble remove --calc-ci and --ci-memory, it seems like an bug with rsem
  rsem: "--estimate-rspd --no-bam-output"
  #You can change the normalization used to generate the bigWig files that will be used in the genome browser
  #Options for --normalizeUsing are:
  #RPKM = Reads Per Kilobase per Million mapped reads; 
  #CPM = Counts Per Million mapped reads, same as CPM in RNA-seq; 
  #BPM = Bins Per Million mapped reads, same as TPM in RNA-seq; 
  #RPGC = reads per genomic content (1x normalization)
  #Remove for no normalization
  #You can also change the bin size (bp), default is already set (50)
  bamcoverage: "--binSize 50 --normalizeUsing BPM"
